services:
  - type: web
    name: power-consumption-api
    env: python
    buildCommand: |
      pip install -r power-consumption-api/requirements.txt
    startCommand: |
      cd power-consumption-api && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0